name: Deploy Azure Function (backend)

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Function App (Flex)
        uses: Azure/functions-action@v1
        with:
          app-name: "rcfuncv2"
          package: "backend"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          sku: flexconsumption
          remote-build: true
          respect-funcignore: true